export const MOCK_RESOURCES = [
  {
    id: "1",
    title: "MIT OpenCourseWare - Advanced Engineering Mathematics",
    description: "Comprehensive course materials covering differential equations, linear algebra, and complex analysis.",
    type: "Study Guide",
    subjects: ["Mathematics", "Engineering"],
    format: "PDF",
    difficulty: "Advanced",
    rating: 4.9,
    downloads: 12500,
    duration: "8 weeks",
    dateAdded: "2024-03-15",
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=500&h=500&fit=crop",
    url: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/mit18_06s10_exam1_s10_soln/"
  },
  {
    id: "2",
    title: "Stanford CS229 - Machine Learning",
    description: "Complete lecture notes and assignments for Stanford's machine learning course.",
    type: "Video Lecture",
    subjects: ["Computer Science", "Artificial Intelligence"],
    format: "Video",
    difficulty: "Advanced",
    rating: 4.8,
    downloads: 9800,
    duration: "10 weeks",
    dateAdded: "2024-03-10",
    thumbnail: "https://images.unsplash.com/photo-1504384764586-bb4cdc1707b0?w=500&h=500&fit=crop",
    url: "https://cs229.stanford.edu/"
  },
  {
    id: "3",
    title: "NPTEL - Control Systems Engineering",
    description: "Comprehensive video lectures on control systems, from basics to advanced topics.",
    type: "Video Lecture",
    subjects: ["Electrical Engineering", "Control Systems"],
    format: "Video",
    difficulty: "Intermediate",
    rating: 4.7,
    downloads: 7500,
    duration: "12 weeks",
    dateAdded: "2024-03-05",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&h=500&fit=crop",
    url: "https://nptel.ac.in/courses/108/106/108106135/"
  },
  {
    id: "4",
    title: "Thermodynamics: An Engineering Approach",
    description: "Complete textbook with solved examples and practice problems.",
    type: "Study Guide",
    subjects: ["Mechanical Engineering", "Thermodynamics"],
    format: "PDF",
    difficulty: "Intermediate",
    rating: 4.8,
    downloads: 21000,
    duration: "6 months",
    dateAdded: "2024-03-01",
    thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=500&fit=crop",
    url: "https://www.mheducation.com/highered/product/thermodynamics-engineering-approach-cengel-boles/M9780073398174.html"
  },
  {
    id: "5",
    title: "Structural Analysis Fundamentals",
    description: "Interactive course covering structural analysis principles and applications.",
    type: "Interactive Quiz",
    subjects: ["Civil Engineering", "Structural Engineering"],
    format: "Interactive",
    difficulty: "Beginner",
    rating: 4.6,
    downloads: 8500,
    duration: "8 weeks",
    dateAdded: "2024-02-28",
    thumbnail: "https://images.unsplash.com/photo-1456735190827-d1262f71b49a?w=500&h=500&fit=crop",
    url: "https://www.coursera.org/learn/structural-analysis"
  },
  {
    id: "6",
    title: "Chemical Engineering Process Control",
    description: "Comprehensive guide to process control in chemical engineering.",
    type: "Study Guide",
    subjects: ["Chemical Engineering", "Process Control"],
    format: "PDF",
    difficulty: "Advanced",
    rating: 4.7,
    downloads: 12000,
    duration: "10 weeks",
    dateAdded: "2024-02-25",
    thumbnail: "https://images.unsplash.com/photo-1505664194779-8beaceb93744?w=500&h=500&fit=crop",
    url: "https://www.sciencedirect.com/book/9780128124801/process-control"
  }
]; 