export const MOCK_TUTORS = [
  {
    id: "1",
    name: "Dr. Sarah Chen",
    subjects: ["Mathematics", "Physics"],
    experience: 8,
    rating: 4.9,
    availability: ["Weekdays", "Evenings"],
    hourlyRate: 1200,
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&h=500&fit=crop",
    bio: "PhD in Applied Mathematics with 8 years of teaching experience. Specializes in calculus, linear algebra, and mathematical physics.",
  },
  {
    id: "2",
    name: "Prof. Rajesh Kumar",
    subjects: ["Computer Science", "Mathematics"],
    experience: 12,
    rating: 4.8,
    availability: ["Weekdays", "Weekends"],
    hourlyRate: 1500,
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&h=500&fit=crop",
    bio: "Professor of Computer Science with expertise in algorithms, data structures, and software development. Passionate about helping students master programming concepts.",
  },
  {
    id: "3",
    name: "Dr. Emily Thompson",
    subjects: ["Biology", "Chemistry"],
    experience: 6,
    rating: 4.7,
    availability: ["Weekdays", "Mornings"],
    hourlyRate: 1000,
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500&h=500&fit=crop",
    bio: "PhD in Molecular Biology with research experience in genetics and biochemistry. Makes complex biological concepts easy to understand.",
  },
  {
    id: "4",
    name: "Mr. Amit Patel",
    subjects: ["Physics", "Chemistry"],
    experience: 5,
    rating: 4.6,
    availability: ["Weekends", "Evenings"],
    hourlyRate: 900,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop",
    bio: "MSc in Physics with a focus on quantum mechanics and thermodynamics. Experienced in helping students prepare for competitive exams.",
  },
  {
    id: "5",
    name: "Dr. Lisa Wang",
    subjects: ["English", "History"],
    experience: 10,
    rating: 4.9,
    availability: ["Weekdays", "Mornings"],
    hourlyRate: 1300,
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&h=500&fit=crop",
    bio: "PhD in English Literature with expertise in academic writing and critical analysis. Helps students improve their writing skills and historical understanding.",
  },
  {
    id: "6",
    name: "Prof. Michael Brown",
    subjects: ["Economics", "Mathematics"],
    experience: 15,
    rating: 4.8,
    availability: ["Weekdays", "Weekends"],
    hourlyRate: 1600,
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&h=500&fit=crop",
    bio: "Professor of Economics with research experience in macroeconomics and econometrics. Expert in helping students understand complex economic concepts.",
  },
]; 